default: &default
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  adapter: postgresql
  host: localhost
  database: db_heroes_development
  port: 5454
  username: postgres
  password: 123456

development:
  <<: *default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3
